# Netlify deployment configuration
[build]
  command = "pnpm run build"

# Production configuration (main branch)
[context.production]
  environment = { NODE_ENV = "production" }
  command = "pnpm run build"

# Staging configuration (staging branch)
[context.staging]
  environment = { NODE_ENV = "staging" }
  command = "pnpm run build"

# Branch deploy configuration (for feature branches)
[context.branch-deploy]
  environment = { NODE_ENV = "development" }
  command = "pnpm run build"

# Deploy preview configuration (for PRs)
[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  command = "pnpm run build"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

# Headers for manifest.json
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

# API routes headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Type = "application/json"

# Redirects to handle trailing slashes and ensure proper routing
[[redirects]]
  from = "https://supermano.ai/*"
  to = "https://www.supermano.ai/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"
