# Netlify deployment configuration
[build]
  command = "pnpm run build"
  functions = "netlify/functions"
  publish = ".next"

# Production configuration (main branch)
[context.production]
  environment = { NODE_ENV = "production" }
  command = "pnpm run build"

# Staging configuration (staging branch)
[context.staging]
  environment = { NODE_ENV = "staging" }
  command = "pnpm run build"

# Branch deploy configuration (for feature branches)
[context.branch-deploy]
  environment = { NODE_ENV = "development" }
  command = "pnpm run build"

# Deploy preview configuration (for PRs)
[context.deploy-preview]
  environment = { NODE_ENV = "development" }
  command = "pnpm run build"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Next.js specific settings
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
